# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-15 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('cuerpo', models.TextField()),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
    ]
